version: '3'
services:
  hugo:
    container_name: khasegawa.net-hugo
    image: khasegawa.net/hugo
    build:
      context: containers/hugo/
    volumes:
      - .:/app:rw
    ports:
      - '1313:1313'
    environment:
      HUGO_BASE_URL: "${HUGO_BASE_URL:-localhost:1313}"
    privileged: true
    command: make run
  webpack:
    container_name: khasegawa.net-webpack
    image: khasegawa.net/webpack
    build:
      context: containers/webpack/
    volumes:
      - .:/app:rw
      - node_modules:/app/node_modules
    ports:
      - '9005:9005'
    privileged: true
    command: npm run watch
volumes:
  node_modules:
