version: 2.1

commands:
  setup:
    steps:
      - run:
          name: Install packages
          command: |
            apt update \
              && apt install -y wget git bash make
      - run:
          name: Install hugo-extended
          command: |
            wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.deb \
              && dpkg -i hugo.deb

executors:
  builder:
    working_directory: /app
    docker:
      - image: ubuntu:20.04
        environment:
          TZ: Asia/Tokyo
  deployer:
    working_directory: /app
    docker:
      - image: node:16
        environment:
          TZ: Asia/Tokyo

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - setup
      - run:
          name: Update submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: Build site
          command: make build
      - persist_to_workspace:
          root: .
          paths:
            - public/*

  deploy:
    executor: deployer
    steps:
      - run:
          name: Install firebase-tools
          command: npm install -g firebase-tools
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Firebase
          command: firebase deploy -p ./public --token "$FIREBASE_TOKEN"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires: [build]
  daily_deploy:
    triggers:
      - schedule:
          cron: "00 16 * * *"
          filters:
            branches:
              only: [main]
    jobs:
      - build
      - deploy:
          requires: [build]
