---

version: 2
jobs:
  build:
    docker:
      - image: golang:1.11
        environment:
          TZ: Asia/Tokyo
    steps:
      - run: date
      - run:
          name: Install Hugo
          command: |
            cd /root
            wget -O hugo.tgz https://github.com/gohugoio/hugo/releases/download/v0.49.2/hugo_0.49.2_Linux-64bit.tar.gz
            tar xzvf hugo.tgz
            mv ./hugo /usr/local/bin/hugo
            cd /root/project
      - checkout
      - run:
          name: Update submodule
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build site
          command: hugo
      - persist_to_workspace:
          root: .
          paths:
            - public/*
      - store_artifacts:
          path: public
  deploy:
    docker:
      - image: node:10
        environment:
          TZ: Asia/Tokyo
    steps:
      - run:
          name: Install firebase-tools
          command: npm install -g firebase-tools
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Firebase
          command: firebase deploy -p ./public --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires: [build]
  cron_build_and_deploy:
    triggers:
      - schedule:
          cron: "00 22 * * *"
          filters:
            branches:
              only: [master]
    jobs:
      - build
      - deploy:
          requires: [build]
