FROM golang:1.11
RUN wget -O hugo.tgz https://github.com/gohugoio/hugo/releases/download/v0.49.2/hugo_0.49.2_Linux-64bit.tar.gz \
	&& tar xzvf hugo.tgz \
	&& mv ./hugo /usr/local/bin/hugo \
	&& mkdir -p /go/src/github.com/corrupt952/khasegawa.net
WORKDIR /go/src/github.com/corrupt952/khasegawa.net
