FROM node:10
RUN npm install -y yarn \
	&& mkdir -p /app
WORKDIR /app
COPY ./dockerfiles/docker-entrypoint-webpack.sh /app/dockerfiles/docker-entrypoint-webpack.sh
ENTRYPOINT ["/app/dockerfiles/docker-entrypoint-webpack.sh"]
